### PR TITLE
feature: api client account creator

### PR DESCRIPTION
**Pull request by elsongabriel**
# Description

Created script to create account and character by the client.
First, you need to change your `accountCreationClientServices` client's config or update config.ini like this:
from
`accountCreationClientServices=https://www.tibia.com/clientservices/accountcreationclientservices.php`
to
`accountCreationClientServices=http://YOURSITE/clientcreateaccount.php`

image

OBS: **Creating characters from this windows, is only available to create in "rook", creating with vocation is not permitted.**

## Type of change

Please delete options that are not relevant.

  - [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested

**Test Configuration**:

  - MyAAC Version: (latest: 0.8.12)
  - Browser: Chrome
  - Operating System: Windows 11

## Checklist

  - [x] My code follows the style guidelines of this project
  - [x] I followed project rules, best practices and code indentation
  - [x] I have performed a self-review of my own code
  - [x] I checked the PR checks reports 
  - [x] I have commented my code, particularly in hard-to-understand areas
  - [x] I have made corresponding changes to the documentation
  - [x] My changes generate no new warnings
  - [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by luancolombo** [comment]
Bom dia, deixando aqui meu feedback..a API ta funcionando perfeitamente fiz varios testes locais, porém unico problema e que quando voce clica em Start Playing não acontece nada, ou seja voce nao tem nenhuma resposta que a conta foi criada, entao voce clica de novo e ai sim aparece um erro que o email e invalido(isso acontece pq a conta foi criada ja porem nao tivemos a resposta do servidor). Mas fora isso ta top.

**Comment by Kasllow** [comment]
I tested mine, the only thing is that it doesn't create the char ;/

**Comment by elsongabriel** [comment]
> I tested mine, the only thing is that it doesn't create the char ;/

I've tested too. In local doesn't create char. but in VPS (production) it does.
Can you check too ? I will review the code again.

**Comment by QuebradaZN** [comment]
> I've tested too. In local doesn't create char. but in VPS (production) it does.
> Can you check too ? I will review the code again.

I ran tests on VPS (Prod) and indeed char cannot be created!

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
